version: "3"
services:
    elm:
        build: .
        container_name: elm
        depends_on: 
            - mongodb
        ports:
            - "8303:8303"
    mongodb:
        container_name: mongodb
        image: mongo
        ports:
            - "27017:27017"